### PR TITLE
Clear up possible confusion

### PR DESCRIPTION
**Pull request by jackdempsey**
As someone new to clojure, the reuse of x made me think that was somehow necessary. Tried it out and realized that of course was silly. So, this small change might help others see it more clearly.

### CODE REVIEW

**Comment by jackdempsey** [comment]
Sigh. I'd --amend that commit and fix my own typo of "their"...but alas, too late.

**Comment by ghost** [comment]
You're just changing x to i here and using it in more than one place.  I'm not sure this really clears up any confusion.  Is there a different or more detailed way to show this?

**Comment by jackdempsey** [comment]
The issue for me was using x a few lines before and binding to x again later. I wasn't sure if it needed to be x again for some reason, or could be a more common variable for holding an integer, say i. Does that make sense? I'm not sure I can come up with a more appropriate variable than i, but I do think it's more useful than repeating x.

**Comment by abedra** [comment]
Ok, i'll buy that for min-1.  I can see how that could possibly be confusing.  There is no need for the change to min-2.  Can you resubmit a patch that just addresses min-1?

**Comment by jackdempsey** [comment]
Not trying to be pedantic, but doesn't it make sense to keep the change in there for min-2? I would wonder why the change back to using x for min-2, and if the "x & more" needed to be repeated, or just as well could have been i again. 

I realize it's a tiny detail but with the concept of things not changing in Clojure and bindings to vars as important as they are, I do think it's worth debating and appreciate the time you're giving to it!

**Comment by abedra** [comment]
Ok, i've pulled this in.  Thanks.

**Comment by jackdempsey** [comment]
Thanks Aaron! Buy you a beer next time you're in SF :-)

**Pull request closed without merging**
